Search.appendIndex(
    [
                {
            "fqsen": "\\route\u0028\u0029",
            "name": "route",
            "summary": "",
            "url": "namespaces/default.html#function_route"
        },                {
            "fqsen": "\\setMetaView\u0028\u0029",
            "name": "setMetaView",
            "summary": "",
            "url": "namespaces/default.html#function_setMetaView"
        },                {
            "fqsen": "\\getArticleData\u0028\u0029",
            "name": "getArticleData",
            "summary": "",
            "url": "namespaces/default.html#function_getArticleData"
        },                {
            "fqsen": "\\getMysqlPDO\u0028\u0029",
            "name": "getMysqlPDO",
            "summary": "",
            "url": "namespaces/default.html#function_getMysqlPDO"
        },                {
            "fqsen": "\\getArticles\u0028\u0029",
            "name": "getArticles",
            "summary": "",
            "url": "namespaces/default.html#function_getArticles"
        },                {
            "fqsen": "\\getArticlePage\u0028\u0029",
            "name": "getArticlePage",
            "summary": "",
            "url": "namespaces/default.html#function_getArticlePage"
        },                {
            "fqsen": "\\getArticlePageByUser\u0028\u0029",
            "name": "getArticlePageByUser",
            "summary": "",
            "url": "namespaces/default.html#function_getArticlePageByUser"
        },                {
            "fqsen": "\\getArticleCount\u0028\u0029",
            "name": "getArticleCount",
            "summary": "",
            "url": "namespaces/default.html#function_getArticleCount"
        },                {
            "fqsen": "\\getArticleCountByUser\u0028\u0029",
            "name": "getArticleCountByUser",
            "summary": "",
            "url": "namespaces/default.html#function_getArticleCountByUser"
        },                {
            "fqsen": "\\getArticleAuthor\u0028\u0029",
            "name": "getArticleAuthor",
            "summary": "",
            "url": "namespaces/default.html#function_getArticleAuthor"
        },                {
            "fqsen": "\\userExists\u0028\u0029",
            "name": "userExists",
            "summary": "",
            "url": "namespaces/default.html#function_userExists"
        },                {
            "fqsen": "\\addUser\u0028\u0029",
            "name": "addUser",
            "summary": "",
            "url": "namespaces/default.html#function_addUser"
        },                {
            "fqsen": "\\checkUserPassword\u0028\u0029",
            "name": "checkUserPassword",
            "summary": "",
            "url": "namespaces/default.html#function_checkUserPassword"
        },                {
            "fqsen": "\\getUserInitials\u0028\u0029",
            "name": "getUserInitials",
            "summary": "",
            "url": "namespaces/default.html#function_getUserInitials"
        },                {
            "fqsen": "\\getUserID\u0028\u0029",
            "name": "getUserID",
            "summary": "",
            "url": "namespaces/default.html#function_getUserID"
        },                {
            "fqsen": "\\addArticle\u0028\u0029",
            "name": "addArticle",
            "summary": "",
            "url": "namespaces/default.html#function_addArticle"
        },                {
            "fqsen": "\\updateArticle\u0028\u0029",
            "name": "updateArticle",
            "summary": "",
            "url": "namespaces/default.html#function_updateArticle"
        },                {
            "fqsen": "\\deleteAricle\u0028\u0029",
            "name": "deleteAricle",
            "summary": "",
            "url": "namespaces/default.html#function_deleteAricle"
        },                {
            "fqsen": "\\getArticleById\u0028\u0029",
            "name": "getArticleById",
            "summary": "",
            "url": "namespaces/default.html#function_getArticleById"
        },                {
            "fqsen": "\\setResetTokenByEmail\u0028\u0029",
            "name": "setResetTokenByEmail",
            "summary": "",
            "url": "namespaces/default.html#function_setResetTokenByEmail"
        },                {
            "fqsen": "\\setResetTokenById\u0028\u0029",
            "name": "setResetTokenById",
            "summary": "",
            "url": "namespaces/default.html#function_setResetTokenById"
        },                {
            "fqsen": "\\getResetToken\u0028\u0029",
            "name": "getResetToken",
            "summary": "",
            "url": "namespaces/default.html#function_getResetToken"
        },                {
            "fqsen": "\\getLastTokenTimestamp\u0028\u0029",
            "name": "getLastTokenTimestamp",
            "summary": "",
            "url": "namespaces/default.html#function_getLastTokenTimestamp"
        },                {
            "fqsen": "\\setUserPasswordByToken\u0028\u0029",
            "name": "setUserPasswordByToken",
            "summary": "",
            "url": "namespaces/default.html#function_setUserPasswordByToken"
        },                {
            "fqsen": "\\setUserPasswordById\u0028\u0029",
            "name": "setUserPasswordById",
            "summary": "",
            "url": "namespaces/default.html#function_setUserPasswordById"
        },                {
            "fqsen": "\\getUserName\u0028\u0029",
            "name": "getUserName",
            "summary": "",
            "url": "namespaces/default.html#function_getUserName"
        },                {
            "fqsen": "\\setUserEmail\u0028\u0029",
            "name": "setUserEmail",
            "summary": "",
            "url": "namespaces/default.html#function_setUserEmail"
        },                {
            "fqsen": "\\getUserEmail\u0028\u0029",
            "name": "getUserEmail",
            "summary": "",
            "url": "namespaces/default.html#function_getUserEmail"
        },                {
            "fqsen": "\\removeUserAccount\u0028\u0029",
            "name": "removeUserAccount",
            "summary": "",
            "url": "namespaces/default.html#function_removeUserAccount"
        },                {
            "fqsen": "\\addImage\u0028\u0029",
            "name": "addImage",
            "summary": "",
            "url": "namespaces/default.html#function_addImage"
        },                {
            "fqsen": "\\updateImageMetaData\u0028\u0029",
            "name": "updateImageMetaData",
            "summary": "",
            "url": "namespaces/default.html#function_updateImageMetaData"
        },                {
            "fqsen": "\\getImageCount\u0028\u0029",
            "name": "getImageCount",
            "summary": "",
            "url": "namespaces/default.html#function_getImageCount"
        },                {
            "fqsen": "\\getImageCountByUserID\u0028\u0029",
            "name": "getImageCountByUserID",
            "summary": "",
            "url": "namespaces/default.html#function_getImageCountByUserID"
        },                {
            "fqsen": "\\getImagePage\u0028\u0029",
            "name": "getImagePage",
            "summary": "",
            "url": "namespaces/default.html#function_getImagePage"
        },                {
            "fqsen": "\\getImagePageByUserID\u0028\u0029",
            "name": "getImagePageByUserID",
            "summary": "",
            "url": "namespaces/default.html#function_getImagePageByUserID"
        },                {
            "fqsen": "\\getImageAuthor\u0028\u0029",
            "name": "getImageAuthor",
            "summary": "",
            "url": "namespaces/default.html#function_getImageAuthor"
        },                {
            "fqsen": "\\getImageUsage\u0028\u0029",
            "name": "getImageUsage",
            "summary": "",
            "url": "namespaces/default.html#function_getImageUsage"
        },                {
            "fqsen": "\\deleteImage\u0028\u0029",
            "name": "deleteImage",
            "summary": "",
            "url": "namespaces/default.html#function_deleteImage"
        },                {
            "fqsen": "\\getImageName\u0028\u0029",
            "name": "getImageName",
            "summary": "",
            "url": "namespaces/default.html#function_getImageName"
        },                {
            "fqsen": "\\getImageMeta\u0028\u0029",
            "name": "getImageMeta",
            "summary": "",
            "url": "namespaces/default.html#function_getImageMeta"
        },                {
            "fqsen": "\\getUserImageFiles\u0028\u0029",
            "name": "getUserImageFiles",
            "summary": "",
            "url": "namespaces/default.html#function_getUserImageFiles"
        },                {
            "fqsen": "\\renameImageFile\u0028\u0029",
            "name": "renameImageFile",
            "summary": "",
            "url": "namespaces/default.html#function_renameImageFile"
        },                {
            "fqsen": "\\updateImageMeta\u0028\u0029",
            "name": "updateImageMeta",
            "summary": "",
            "url": "namespaces/default.html#function_updateImageMeta"
        },                {
            "fqsen": "\\checkLogin\u0028\u0029",
            "name": "checkLogin",
            "summary": "",
            "url": "namespaces/default.html#function_checkLogin"
        },                {
            "fqsen": "\\setLoggedin\u0028\u0029",
            "name": "setLoggedin",
            "summary": "",
            "url": "namespaces/default.html#function_setLoggedin"
        },                {
            "fqsen": "\\setInitials\u0028\u0029",
            "name": "setInitials",
            "summary": "",
            "url": "namespaces/default.html#function_setInitials"
        },                {
            "fqsen": "\\setUserID\u0028\u0029",
            "name": "setUserID",
            "summary": "",
            "url": "namespaces/default.html#function_setUserID"
        },                {
            "fqsen": "\\getUserIDSession\u0028\u0029",
            "name": "getUserIDSession",
            "summary": "",
            "url": "namespaces/default.html#function_getUserIDSession"
        },                {
            "fqsen": "\\getLoginAttempts\u0028\u0029",
            "name": "getLoginAttempts",
            "summary": "",
            "url": "namespaces/default.html#function_getLoginAttempts"
        },                {
            "fqsen": "\\setLoginAttempt\u0028\u0029",
            "name": "setLoginAttempt",
            "summary": "",
            "url": "namespaces/default.html#function_setLoginAttempt"
        },                {
            "fqsen": "\\setUserLoggedinData\u0028\u0029",
            "name": "setUserLoggedinData",
            "summary": "",
            "url": "namespaces/default.html#function_setUserLoggedinData"
        },                {
            "fqsen": "\\setLastArticleWrite\u0028\u0029",
            "name": "setLastArticleWrite",
            "summary": "",
            "url": "namespaces/default.html#function_setLastArticleWrite"
        },                {
            "fqsen": "\\getLastArticleWrite\u0028\u0029",
            "name": "getLastArticleWrite",
            "summary": "",
            "url": "namespaces/default.html#function_getLastArticleWrite"
        },                {
            "fqsen": "\\setSelectedImage\u0028\u0029",
            "name": "setSelectedImage",
            "summary": "",
            "url": "namespaces/default.html#function_setSelectedImage"
        },                {
            "fqsen": "\\getSelectedImage\u0028\u0029",
            "name": "getSelectedImage",
            "summary": "",
            "url": "namespaces/default.html#function_getSelectedImage"
        },                {
            "fqsen": "\\printArticlesbyUserId\u0028\u0029",
            "name": "printArticlesbyUserId",
            "summary": "",
            "url": "namespaces/default.html#function_printArticlesbyUserId"
        },                {
            "fqsen": "\\redirectClient\u0028\u0029",
            "name": "redirectClient",
            "summary": "",
            "url": "namespaces/default.html#function_redirectClient"
        },                {
            "fqsen": "\\getPathOverBase\u0028\u0029",
            "name": "getPathOverBase",
            "summary": "",
            "url": "namespaces/default.html#function_getPathOverBase"
        },                {
            "fqsen": "\\sendLostPasswordEmail\u0028\u0029",
            "name": "sendLostPasswordEmail",
            "summary": "",
            "url": "namespaces/default.html#function_sendLostPasswordEmail"
        },                {
            "fqsen": "\\sendChangeEmailToken\u0028\u0029",
            "name": "sendChangeEmailToken",
            "summary": "",
            "url": "namespaces/default.html#function_sendChangeEmailToken"
        },                {
            "fqsen": "\\sendDeleteAccountToken\u0028\u0029",
            "name": "sendDeleteAccountToken",
            "summary": "",
            "url": "namespaces/default.html#function_sendDeleteAccountToken"
        },                {
            "fqsen": "\\returnAlert\u0028\u0029",
            "name": "returnAlert",
            "summary": "",
            "url": "namespaces/default.html#function_returnAlert"
        },                {
            "fqsen": "\\checkCaptcha\u0028\u0029",
            "name": "checkCaptcha",
            "summary": "",
            "url": "namespaces/default.html#function_checkCaptcha"
        },                {
            "fqsen": "\\printImages\u0028\u0029",
            "name": "printImages",
            "summary": "",
            "url": "namespaces/default.html#function_printImages"
        },                {
            "fqsen": "\\getImageUrl\u0028\u0029",
            "name": "getImageUrl",
            "summary": "",
            "url": "namespaces/default.html#function_getImageUrl"
        },                {
            "fqsen": "\\getCurrentGitCommit\u0028\u0029",
            "name": "getCurrentGitCommit",
            "summary": "",
            "url": "namespaces/default.html#function_getCurrentGitCommit"
        },                {
            "fqsen": "\\printGitInfo\u0028\u0029",
            "name": "printGitInfo",
            "summary": "",
            "url": "namespaces/default.html#function_printGitInfo"
        },                {
            "fqsen": "\\checkMaxPage\u0028\u0029",
            "name": "checkMaxPage",
            "summary": "",
            "url": "namespaces/default.html#function_checkMaxPage"
        },                {
            "fqsen": "\\getPagNumber\u0028\u0029",
            "name": "getPagNumber",
            "summary": "",
            "url": "namespaces/default.html#function_getPagNumber"
        },                {
            "fqsen": "\\printStaticPagination\u0028\u0029",
            "name": "printStaticPagination",
            "summary": "",
            "url": "namespaces/default.html#function_printStaticPagination"
        },                {
            "fqsen": "\\printDynamicPagination\u0028\u0029",
            "name": "printDynamicPagination",
            "summary": "",
            "url": "namespaces/default.html#function_printDynamicPagination"
        },                {
            "fqsen": "\\printPaginationButton\u0028\u0029",
            "name": "printPaginationButton",
            "summary": "",
            "url": "namespaces/default.html#function_printPaginationButton"
        },                {
            "fqsen": "\\printFirstPage\u0028\u0029",
            "name": "printFirstPage",
            "summary": "",
            "url": "namespaces/default.html#function_printFirstPage"
        },                {
            "fqsen": "\\printLastPage\u0028\u0029",
            "name": "printLastPage",
            "summary": "",
            "url": "namespaces/default.html#function_printLastPage"
        },                {
            "fqsen": "\\printPagination\u0028\u0029",
            "name": "printPagination",
            "summary": "",
            "url": "namespaces/default.html#function_printPagination"
        },                {
            "fqsen": "\\getPaginationVisibility\u0028\u0029",
            "name": "getPaginationVisibility",
            "summary": "",
            "url": "namespaces/default.html#function_getPaginationVisibility"
        },                {
            "fqsen": "\\googleLogin\u0028\u0029",
            "name": "googleLogin",
            "summary": "",
            "url": "namespaces/default.html#function_googleLogin"
        },                {
            "fqsen": "\\getGoogleProfile\u0028\u0029",
            "name": "getGoogleProfile",
            "summary": "",
            "url": "namespaces/default.html#function_getGoogleProfile"
        },                {
            "fqsen": "\\githubLogin\u0028\u0029",
            "name": "githubLogin",
            "summary": "",
            "url": "namespaces/default.html#function_githubLogin"
        },                {
            "fqsen": "\\getGithubProfile\u0028\u0029",
            "name": "getGithubProfile",
            "summary": "",
            "url": "namespaces/default.html#function_getGithubProfile"
        },                {
            "fqsen": "\\twitterLogin\u0028\u0029",
            "name": "twitterLogin",
            "summary": "",
            "url": "namespaces/default.html#function_twitterLogin"
        },                {
            "fqsen": "\\getTwitterProfile\u0028\u0029",
            "name": "getTwitterProfile",
            "summary": "",
            "url": "namespaces/default.html#function_getTwitterProfile"
        },                {
            "fqsen": "\\socialLoginUser\u0028\u0029",
            "name": "socialLoginUser",
            "summary": "",
            "url": "namespaces/default.html#function_socialLoginUser"
        },                {
            "fqsen": "\\returnError\u0028\u0029",
            "name": "returnError",
            "summary": "",
            "url": "namespaces/default.html#function_returnError"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
